name: vlc
adopt-info: vlc
grade: stable
base: core24
summary: Read, capture, broadcast your multimedia streams
description: |
  VLC is a free and open source cross-platform multimedia player and
  framework that plays most multimedia files as well as DVDs, Audio CDs,
  VCDs, and various streaming protocols.
  NOTE. This snap contains an untested daily build of VLC
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/asound.conf:
    bind-file: $SNAP/etc/asound.conf

plugs:
  dot-config-aacs:
    interface: personal-files
    read:
    - $HOME/.config/aacs

apps:
  vlc:
    desktop: usr/share/applications/vlc.desktop
    command-chain: [bin/desktop-launch]
    command: bin/vlc-snap-wrapper.sh
    common-id: org.videolan.vlc
    plugs:
      - alsa
      - network
      - network-bind
      - home
      - opengl
      - mount-observe
      - optical-drive
      - camera
      - removable-media
      - screen-inhibit-control
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - dvb
      - audio-playback
      - audio-record
      - avahi-control
      - dot-config-aacs
    slots:
      - mpris
    environment:
      DISABLE_WAYLAND: 1

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2t64
      - libasound2-plugins
      - yad
    stage:
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libasound*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdnsfile*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libFLAC*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjack*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpulse*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamplerate*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libspeex*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvorbis*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
  deps:
    plugin: nil
    stage-packages:
      - libarchive13t64
      - libatomic1
      - libavahi-common3
      - libavcodec-extra60
      - libavcodec60
      - libavformat-extra60
      - libavformat60
      - libavutil58
      - libdrm2
      - libflac++10
      - libflac12t64
      - libfribidi0
      - libgl1
      - libgtk-3-0t64
      - libharfbuzz0b
      - libidn12
      - libixml11t64
      - liblua5.2-0
      - libmtp9t64
      - libnotify4
      - liboggplay1
      - libpipewire-0.3-0t64
      - libproxy1v5
      - libpulse0
      - libqt6qml6
      - libqt6qmlcore6
      - libqt6qmllocalstorage6
      - libqt6qmlmodels6
      - libqt6qmlworkerscript6
      - libqt6quick6
      - libqt6quickcontrols2-6
      - libqt6quickcontrols2impl6
      - libqt6quickdialogs2-6
      - libqt6quickdialogs2quickimpl6
      - libqt6quickdialogs2utils6
      - libqt6quicklayouts6
      - libqt6quickparticles6
      - libqt6quickshapes6
      - libqt6quicktemplates2-6
      - libqt6quickwidgets6
      - libqt6svg6
      - libqt6webenginecore6-bin
      - librsvg2-2
      - libsecret-1-0
      - libsmbclient
      - libswscale7
      - libupnp17t64
      - libva-wayland2
      - libvpx9
      - libx264-164
      - libx265-199
      - libxcb-composite0
      - libxcb-damage0
      - libxcb-xv0
      - libxcursor1
      - libxinerama1
      - libxkbcommon0
      - libxpm4
      - libzvbi0t64
      - locales-all
      - mesa-utils
      - primus-libs
      - qml6-module-qtqml
      - qml6-module-qtqml-models
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-layouts
      - qml6-module-qtquick-templates
      - qml6-module-qtquick-window
      - qt6-image-formats-plugins
      - qt6-wayland
      - shared-mime-info
      - xkb-data
    prime:
      - -usr/lib/*/cmake
      - -usr/include
      - -usr/share/ECM
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/X11
      - -usr/lib/gcc
      - -usr/lib/aspell
      - -usr/lib/*/qt5
      - -usr/lib/*/*Qt5*
      - -usr/lib/carla*
      - -usr/lib/python3/dist-packages/PyQt5
  wrapper:
    plugin: nil
    source: snap/local
    override-build: |
      mkdir -p $CRAFT_PRIME/bin
      cp -p $CRAFT_PROJECT_DIR/snap/local/desktop-launch $CRAFT_PRIME/bin/
      cp -p $CRAFT_PROJECT_DIR/snap/local/vlc-snap-wrapper.sh $CRAFT_PRIME/bin/
      chmod a+x $CRAFT_PRIME/bin/{desktop-launch,vlc-snap-wrapper.sh}
  vlc:
    source: https://code.videolan.org/videolan/vlc.git
    source-type: git
    source-branch: master
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-qt
      - --enable-wayland
      - --enable-pipewire
      - --enable-pulse
      - --enable-avcodec
      - --enable-avformat
      - --enable-swscale
      - --enable-ogg
      - --enable-mpg123
      - --enable-flac
      - --enable-vorbis
      - --enable-x264
      - --enable-x265
      - --enable-vpx
      - --enable-dav1d
      - --enable-xcb
      - --enable-vulkan
      - --enable-lua
      - --disable-oss
      - --disable-avahi
      - --disable-jack
      #- --disable-smbclient
      #- --disable-samba
      - --disable-replace-samba
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --always HEAD)
    override-build: |
      craftctl default
      sed -i 's|/root/parts/vlc/install|$SNAP|g' $CRAFT_PART_INSTALL/usr/bin/{c,n,r}vlc
      sed -i 's|Icon=vlc|Icon=/usr/share/icons/hicolor/256x256/apps/vlc\.png|' $CRAFT_PART_INSTALL/usr/share/applications/vlc.desktop
      sed -i 's|TryExec=.*|TryExec=/snap/bin/vlc|' $CRAFT_PART_INSTALL/usr/share/applications/vlc.desktop
      find  $CRAFT_PART_INSTALL/ -type f -name '*.la' -delete
    build-packages:
      - autopoint
      - bison
      - build-essential
      - dpkg-dev
      - flex
      - gettext
      - git
      - intltool
      - libarchive-dev
      - libasound2-dev
      - libaudio-dev
      - libavahi-client-dev
      - libavformat-dev
      - libcdio-dev
      - libdav1d-dev
      - libdbus-1-dev
      - libdirectfb-dev
      - libflac-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libgcrypt20-dev
      - libgnutls28-dev
      - libharfbuzz-dev
      - libidn11-dev
      - libltdl-dev
      - liblua5.2-dev
      - libmpg123-dev
      - libmtp-dev
      - libncursesw5-dev
      - libnotify-dev
      - libogg-dev
      - libopenal-dev
      - libpipewire-0.3-dev
      - libpng-dev
      - libpulse-dev
      - libqt6svg6-dev
      - librsvg2-dev
      - libsecret-1-dev
      - libsmbclient-dev
      - libswscale-dev
      - libsystemd-dev
      - libtool
      - libudev-dev
      - libupnp-dev
      - libv4l-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libvulkan-dev
      - libx11-dev
      - libx264-dev
      - libx265-dev
      - libxcb-composite0-dev
      - libxcb-damage0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxcb-xv0-dev
      - libxcb1-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-x11-dev
      - libxpm-dev
      - libzvbi-dev
      - lua5.2
      - make
      - pkg-config
      - portaudio19-dev
      - qml6-module-qtqml
      - qml6-module-qtqml-models
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-layouts
      - qml6-module-qtquick-window
      - qt6-base-dev
      - qt6-base-private-dev
      - qt6-declarative-dev
      - qt6-declarative-dev-tools
      - qt6-qpa-plugins
      - qt6-quick3d-dev-tools
      - qt6-shader-baker
      - qt6-tools-dev-tools
      - qt6-wayland-dev
      - wayland-protocols
      - xz-utils
      - zlib1g-dev
